#!/usr/bin/env bash
#
# Wizard: configura o projeto Vercel e os secrets do GitHub para previews.
# Generated by the /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Você controla o navegador; este wizard diz exatamente o que fazer e\n' "$DIM"
  printf '  captura os valores que copiar de volta. Pode parar com Ctrl-C e\n'
  printf '  continuar depois, pois valores já salvos são lembrados.%s\n' "$RESET"
  pause "Pronto para começar?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Etapa %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ abrindo%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "não foi possível abrir o navegador; acesse manualmente: $url"; fi
  } >/dev/null 2>&1 || warn "não foi possível abrir o navegador; acesse manualmente: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Pressione Enter para continuar}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [s/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Ss] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter mantém atual]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter mantém atual]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ escreveu%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ definiu%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (defina manualmente: gh secret set $name)")
  warn "pulou GitHub secret $name: gh não está pronto; defina depois"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ definiu%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "pulou GitHub variable $name: gh não está pronto; defina depois"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Configuração concluída%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "escreveu ${#WRITTEN_ENV[@]} valor(es) em $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "definiu ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "ainda precisa fazer manualmente:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: configuração do preview Vercel para apoio-tdah.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Configuração do preview Vercel"

stage "Vincular projeto na Vercel"
say "Vamos criar ou vincular o projeto Vercel para este repositório."
step "Execute no terminal: npx --yes vercel@61.1.0 link"
note "Isso abre o navegador para login e importação de klaczok/apoio-tdah."
note "Escolha/crie o projeto 'apoio-tdah' quando solicitado."
pause "Quando o comando terminar e o arquivo .vercel/project.json existir, pressione Enter."

stage "Coletar identificadores do projeto"
if [ ! -f .vercel/project.json ]; then
  warn ".vercel/project.json não encontrado. Verifique o passo anterior."
  exit 1
fi

VERCEL_ORG_ID=$(node -e "console.log(require('./.vercel/project.json').orgId)")
VERCEL_PROJECT_ID=$(node -e "console.log(require('./.vercel/project.json').projectId)")

say "orgId encontrado: $VERCEL_ORG_ID"
say "projectId encontrado: $VERCEL_PROJECT_ID"

write_env VERCEL_ORG_ID "$VERCEL_ORG_ID"
write_env VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"

stage "Criar token de acesso Vercel"
say "Agora precisamos de um token para o workflow de CI fazer deploys."
open_url "https://vercel.com/account/tokens"
step "Clique em 'Create Token', dê o nome 'apoio-tdah-ci' e copie o valor."
step "Se estiver em um time, use Settings → Tokens do time correspondente."
ask_secret VERCEL_TOKEN "Cole o token aqui:"

write_env VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"

finish
